# Image Segmentation

Segmentation--Partitioning images into different regions..

contours:- They are continuous lines or curves that bound or cover the full bounadary of an object in an image.

In [9]:
import cv2
import numpy as np

img=cv2.imread('images/shapes_donut.jpg')
cv2.imshow('Original',img)
cv2.waitKey(0)

# Grayscaling the Image
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# finding the canny edges
edged=cv2.Canny(gray,30,200)
cv2.imshow('Canny Edges',edged)
cv2.waitKey(0)

# Finding Contours

contours,hierarchy=cv2.findContours(edged.copy(),cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cv2.imshow('Canny edges after Contouring',edged)
cv2.waitKey(0)

print('Number of Contours found = ' + str(len(contours)))

# Drawing the contours
cv2.drawContours(img,contours,-1,(0,255,0),3)
 

cv2.imshow('Contours',img)
cv2.waitKey(0)
print(hierarchy)
print(contours)
cv2.destroyAllWindows()

Number of Contours found = 8
[[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [ 3  1 -1 -1]
  [ 4  2 -1 -1]
  [ 5  3 -1 -1]
  [ 6  4 -1 -1]
  [ 7  5 -1 -1]
  [-1  6 -1 -1]]]
[array([[[368, 157]],

       [[486, 157]],

       [[487, 158]],

       [[492, 158]],

       [[493, 159]],

       [[492, 160]],

       [[492, 295]],

       [[493, 296]],

       [[493, 298]],

       [[492, 299]],

       [[492, 300]],

       [[493, 301]],

       [[491, 303]],

       [[488, 303]],

       [[487, 302]],

       [[368, 302]],

       [[367, 301]],

       [[367, 297]],

       [[366, 296]],

       [[366, 159]]], dtype=int32), array([[[368, 157]],

       [[366, 159]],

       [[366, 296]],

       [[367, 297]],

       [[367, 302]],

       [[487, 302]],

       [[488, 303]],

       [[491, 303]],

       [[493, 301]],

       [[492, 300]],

       [[492, 299]],

       [[493, 298]],

       [[493, 296]],

       [[492, 295]],

       [[492, 160]],

       [[493, 159]],

       [[492, 158]],

       [[487

# Sorting Contours

It is quite useful when doing image processing

# sort by Area:-
It can assist in Object Recoginition

    1.Eliminate small contours that may arise.
    2.Extract the largest contour.
    
# Sorting by spatial position :-

    1.Sort charachters left to right.
    2.Process images in specific order.

 

In [10]:
image=cv2.imread('images/bunchofshapes.jpg')
cv2.imshow('Original',image)
cv2.waitKey(0)

# create a black images with same dimensions as our Loaded image
blank_image = np.zeros((image.shape[0],image.shape[1],3))

original_image=image

gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

edged=cv2.Canny(gray,50,200)
cv2.imshow('Canny Edges',edged)
cv2.waitKey(0)

contours,hierarchy = cv2.findContours(edged.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
print("Number of contours = ", len(contours))


# Drawing all contours over blank_image
cv2.drawContours(blank_image,contours,-1,(0,255,0),3)
cv2.imshow('All Contours',blank_image)
cv2.waitKey(0)

# Drawing all Contours over the original image..
cv2.drawContours(image,contours,-1,(0,255,0),3)
cv2.imshow('Contouring over the BGR Image',image)
cv2.waitKey(0)

cv2.destroyAllWindows()

Number of contours =  4


In [11]:
import numpy as np

# getting the areas of contours
def get_contour_areas(contours):
        all_areas=[]
        for cnt in contours:
            area = cv2.contourArea(cnt)
            all_areas.append(area)
        return all_areas
    
# loading the image
img=cv2.imread('images/bunchofshapes.jpg')
original_img = img

print('Contour Areas before sorting')
print(get_contour_areas(contours))


# Sorting Areas LArge to small 

sorted_contours = sorted(contours,key=cv2.contourArea,reverse=True)

print('Contour Areas before sorting')
print(get_contour_areas(sorted_contours))

# iterating over contours and drawing one at a time 

for c in sorted_contours:
    cv2.drawContours(original_img,[c],-1,(0,255,0),3)
    cv2.waitKey(0)
    cv2.imshow('Contours BY Area',original_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

Contour Areas before sorting
[20587.5, 22900.5, 66581.5, 90222.0]
Contour Areas before sorting
[90222.0, 66581.5, 22900.5, 20587.5]
